Add BPM.
lsst/lsst-texmf pull request #1290
Opened 2024-11-13 15:59 UTC by ktlim

2024-11-13 16:44 UTC, womullan requested changes
can you add spanish also ? (trying to keep it complete)  
Mapa de píxeles defectuoso

2024-11-13 19:06 UTC, ktlim commented
@womullan OK, done (and some syntax problems fixed).

2024-11-13 20:04 UTC, womullan reviewed
thanks for catching the comma;s .. i guess i should have a check for that like i do in english

2024-11-13 20:04 UTC, womullan commented on etc/glossarydefs_es.csv
> -CAM,CÁMara,DM
If you remove the tag from here it will break the translation - CAM is overloaded and the TAG breaks the confusion of which translation to use. SO either we put CAM on both or with put DM on both it can not be blank - most docs use DM as default and usually we will want Camera not Control Account Manager ..   I would be ok tagging Camera at "Gen" and Control Account Manager as "PMO" but it must be consistent in both english and spanish files

2024-11-13 20:04 UTC, womullan commented on etc/glossarydefs_es.csv
> -OSS,Especificaciones del sistema de observatorios; LSE-30,DM
same issue - tags have to match

2024-11-14 15:47 UTC, ktlim commented on etc/glossarydefs_es.csv
> -CAM,CÁMara,DM
Sounds like we need a linter to make sure tags match up and that identical items have different tags...

2024-11-14 15:47 UTC, ktlim commented on etc/glossarydefs_es.csv
> -OSS,Especificaciones del sistema de observatorios; LSE-30,DM
Reverted these.

2024-11-14 15:48 UTC, ktlim commented on etc/glossarydefs_es.csv
> -CAM,CÁMara,DM
Oh, or did it check and I missed the failure?

2024-11-14 21:36 UTC, womullan approved these changes

2024-11-14 21:56 UTC, merged