Tickets/dm 38790 - add memo
lsst/lsst-texmf pull request #769
Opened 2023-04-20 18:24 UTC by womullan

2023-04-20 21:20 UTC, leannep requested changes
Thank you for this - I have taken it for a test run and made a few proposed change

2023-04-20 21:20 UTC, leannep commented on texmf/tex/latex/lsst/lsstdoc.cls
> +        \large
```suggestion
        \begin{flushright}
        \vspace*{-50pt}
        \large 
```

2023-04-20 21:20 UTC, leannep commented on texmf/tex/latex/lsst/lsstdoc.cls
> +        \begin{minipage}{0.2\textwidth}
```suggestion
        \begin{minipage}{0.3\textwidth}
```

2023-04-20 21:20 UTC, leannep commented on texmf/tex/latex/lsst/lsstdoc.cls
> +        \includegraphics[width=2.5cm]{rubin_logo}
```suggestion
        \includegraphics[width=4.0cm]{rubin_logo}
```

2023-04-20 21:20 UTC, leannep commented on texmf/tex/latex/lsst/lsstdoc.cls
> +        \color{lssttitle}
```suggestion
        \color{black}
```

2023-04-20 21:20 UTC, leannep commented on texmf/tex/latex/lsst/lsstdoc.cls
> +        950 Cherry Ave.,
```suggestion
        950 North Cherry Avenue \\
```

2023-04-20 21:20 UTC, leannep commented on texmf/tex/latex/lsst/lsstdoc.cls
> +        85719 Tucson.
```suggestion
        Tucson, AZ, 85719 \\
```

2023-04-20 21:20 UTC, leannep commented on texmf/tex/latex/lsst/lsstdoc.cls
> +	\docDate
```suggestion
	\vspace{3mm}
	\textbf{\docDate} 
	\end{flushright}
```

2023-04-20 21:20 UTC, leannep commented on texmf/tex/latex/lsst/lsstdoc.cls
> +        \textbf {Subject: \@title }\\
```suggestion

        \textbf {Subject: \@title }\\
```

2023-04-21 18:21 UTC, womullan commented on texmf/tex/latex/lsst/lsstdoc.cls
> +        \color{lssttitle}
i liked the teal, but ok

2023-04-21 18:29 UTC, womullan commented
changes incorporated

2023-04-21 18:33 UTC, merged